In [20]:
import pandas as pd
import pymongo

In [21]:
import os

print(os.getcwd())

c:\Users\ayush\Desktop\ML-OPS\Instructor-Performance-Analytics\notebook

In [22]:
df=pd.read_csv("instructor_effectiveness_dataset_2000_rows - instructor_effectiveness_dataset_2000_rows.csv.csv")

df.head()

,batch_id,instructor_id,course_id,completion_rate,avg_score_improvement,avg_quiz_score,dropout_rate,avg_watch_time,assignment_submission_rate,forum_activity_rate,avg_feedback_score,feedback_response_rate
0,B_1861,I_044,C_01,0.300000,14.225955,73.546528,0.647423,0.774572,0.790918,0.108414,3.766211,0.533193
1,B_0354,I_119,C_06,0.657220,22.871110,77.312331,0.425098,0.494936,0.998566,0.280550,5.000000,0.734087
2,B_1334,I_050,C_03,0.300000,16.087517,79.563687,0.700000,0.977901,0.807298,0.207013,3.517386,0.681433
3,B_0906,I_024,C_21,0.639507,24.260687,99.295316,0.334657,0.846515,0.544555,0.306395,4.207578,1.000000
4,B_1290,I_001,C_08,0.527302,31.081556,99.393425,0.521099,0.917450,0.865885,0.252289,4.426230,0.696710

In [23]:
import os

print(os.listdir())

['instructor_effectiveness_dataset_2000_rows - instructor_effectiveness_dataset_2000_rows.csv.csv', 'mongoDB_demo.ipynb']

In [24]:
# df should be converted into dict before we push it to mongodb

data = df.to_dict(orient='records')
# data

In [ ]:
DB_NAME = "Proj2"
COLLECTION_NAME = "Proj2-Data"
CONNECTION_URL = "mongodb+srv://ayush1337yadav_db_user:<db_password>@cluster0.fsbxxkm.mongodb.net/?appName=Cluster0"

# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github

In [29]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [31]:
rec = collection.insert_many(data)

In [32]:
df = pd.DataFrame(list(collection.find()))
df.head()

,_id,batch_id,instructor_id,course_id,completion_rate,avg_score_improvement,avg_quiz_score,dropout_rate,avg_watch_time,assignment_submission_rate,forum_activity_rate,avg_feedback_score,feedback_response_rate
0,6a59c71c661b337924cf66a2,B_1861,I_044,C_01,0.300000,14.225955,73.546528,0.647423,0.774572,0.790918,0.108414,3.766211,0.533193
1,6a59c71c661b337924cf66a3,B_0354,I_119,C_06,0.657220,22.871110,77.312331,0.425098,0.494936,0.998566,0.280550,5.000000,0.734087
2,6a59c71c661b337924cf66a4,B_1334,I_050,C_03,0.300000,16.087517,79.563687,0.700000,0.977901,0.807298,0.207013,3.517386,0.681433
3,6a59c71c661b337924cf66a5,B_0906,I_024,C_21,0.639507,24.260687,99.295316,0.334657,0.846515,0.544555,0.306395,4.207578,1.000000
4,6a59c71c661b337924cf66a6,B_1290,I_001,C_08,0.527302,31.081556,99.393425,0.521099,0.917450,0.865885,0.252289,4.426230,0.696710